services:
  postgres:
    image: postgres:latest
    container_name: {{project-name}}_postgres
    environment:
      POSTGRES_DB: {{pg_db_name}}
      POSTGRES_USER: {{pg_user}}
      POSTGRES_PASSWORD: {{pg_password}}
    ports:
      - "5432:5432"
    volumes:
      - {{project-name}}_postgres_data:/var/lib/postgresql/data

volumes:
  {{project-name}}_postgres_data:
